apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mynetwork
  labels:
    app: nginxx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginxx
  template:
    metadata:
      labels:
        app: nginxx
    spec:
      containers:
      - name: nginxx
        image: nginx:latest
        # image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mynetwork
  labels:
    app: nginxx
spec:
  type: LoadBalancer
  selector:
    app: nginxx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80